In [1]:
import pandas as pd

In [5]:
print("May take a few seconds!")

csv_path = "../MTA_Subway_Hourly_Ridership_Jan_Through_May_2025.csv"

df = pd.read_csv(csv_path, low_memory=False)

In [9]:
# identify unique station/lat/long entries
unique_station_complex_latlong = df[['station_complex', 'station_complex_id', 'latitude', 'longitude']].drop_duplicates().reset_index(drop= True)

# number of lat/long entries per station
latlongs_per_complex = unique_station_complex_latlong.groupby(['station_complex', 'station_complex_id']).size().reset_index()

# culprits
more_than_one_latlong = latlongs_per_complex[latlongs_per_complex[0] > 1].sort_values(by = 0, ascending = False).rename(columns={0: 'num_unique_lat_long_pairs'}).reset_index(drop=True)

more_than_one_latlong

,station_complex,station_complex_id,num_unique_lat_long_pairs
0,"Fulton St (A,C,J,Z,2,3,4,5)",628,8
1,"Canal St (J,N,Q,R,W,Z,6)",623,6
2,"Court Sq (E,G,M,7)",606,6
3,"Times Sq-42 St (N,Q,R,W,S,1,2,3,7)/42 St (A,C,E)",611,6
4,"Court St (R)/Borough Hall (2,3,4,5)",620,5
5,"14 St (F,M,1,2,3)/6 Av (L)",601,4
6,"Chambers St (A,C)/WTC (E)/Park Pl (2,3)/Cortla...",624,4
7,"161 St-Yankee Stadium (B,D,4)",604,3
8,"14 St-Union Sq (L,N,Q,R,W,4,5,6)",602,3
9,New Utrecht Av (N)/62 St (D),615,3
10,"74-Broadway (7)/Jackson Hts-Roosevelt Av (E,F,...",616,3
11,"Atlantic Av-Barclays Ctr (B,D,N,Q,R,2,3,4,5)",617,3
12,"Bryant Pk (B,D,F,M)/5 Av (7)",609,3
13,"Delancey St (F)/Essex St (J,M,Z)",625,3
14,"Jay St-MetroTech (A,C,F,R)",636,3
15,"South Ferry (1)/Whitehall St (R,W)",635,2
16,Lorimer St (L)/Metropolitan Av (G),629,2
17,"Lexington Av-53 St (E,M)/51 St (6)",612,2
18,"Lexington Av (N,R,W)/59 St (4,5,6)",613,2
19,"168 St (A,C,1)",605,2
20,"Franklin Av (2,3,4,5)/Botanic Garden (S)",626,2
21,"34 St-Herald Sq (B,D,F,M,N,Q,R,W)",607,2
22,"Brooklyn Bridge-City Hall (4,5,6)/Chambers St ...",622,2
23,"Broadway-Lafayette St (B,D,F,M)/Bleecker St (6)",619,2
24,"59 St-Columbus Circle (A,B,C,D,1)",614,2
25,"4 Av (F,G)/9 St (R)",608,2
26,"14 St (A,C,E)/8 Av (L)",618,2

In [17]:
# Court Sq., 01/16/2025 at 01:00:00PM

check = df[(df["transit_timestamp"] == '01/16/2025 01:00:00 PM') & (df['station_complex_id'] == '606')].reset_index(drop=True)
check

,transit_timestamp,transit_mode,station_complex_id,station_complex,borough,payment_method,fare_class_category,ridership,transfers,latitude,longitude,Georeference
0,01/16/2025 01:00:00 PM,subway,606,"Court Sq (E,G,M,7)",Queens,metrocard,Metrocard - Full Fare,60,1,40.747845,-73.94383,POINT (-73.94383 40.747845)
1,01/16/2025 01:00:00 PM,subway,606,"Court Sq (E,G,M,7)",Queens,metrocard,Metrocard - Fair Fare,19,0,40.747845,-73.94383,POINT (-73.94383 40.747845)
2,01/16/2025 01:00:00 PM,subway,606,"Court Sq (E,G,M,7)",Queens,omny,OMNY - Seniors & Disability,2,1,40.747845,-73.94600,POINT (-73.946 40.747845)
3,01/16/2025 01:00:00 PM,subway,606,"Court Sq (E,G,M,7)",Queens,metrocard,Metrocard - Unlimited 30-Day,58,0,40.747845,-73.94383,POINT (-73.94383 40.747845)
4,01/16/2025 01:00:00 PM,subway,606,"Court Sq (E,G,M,7)",Queens,metrocard,Metrocard - Unlimited 7-Day,47,0,40.747845,-73.94383,POINT (-73.94383 40.747845)
5,01/16/2025 01:00:00 PM,subway,606,"Court Sq (E,G,M,7)",Queens,metrocard,Metrocard - Other,26,0,40.747845,-73.94383,POINT (-73.94383 40.747845)
6,01/16/2025 01:00:00 PM,subway,606,"Court Sq (E,G,M,7)",Queens,omny,OMNY - Students,59,0,40.747845,-73.94383,POINT (-73.94383 40.747845)
7,01/16/2025 01:00:00 PM,subway,606,"Court Sq (E,G,M,7)",Queens,omny,OMNY - Full Fare,512,22,40.747845,-73.94383,POINT (-73.94383 40.747845)
8,01/16/2025 01:00:00 PM,subway,606,"Court Sq (E,G,M,7)",Queens,metrocard,Metrocard - Seniors & Disability,25,1,40.747845,-73.94383,POINT (-73.94383 40.747845)
9,01/16/2025 01:00:00 PM,subway,606,"Court Sq (E,G,M,7)",Queens,omny,OMNY - Other,1,0,40.747845,-73.94600,POINT (-73.946 40.747845)